words = [
    "attribs",
    "constexpr",
    "deletors",
    "dsl",
    "emplaced",
    "eray",
    "glf",
    "glfw",
    "glfw's",
    "imgui",
    "infos",
    "khr",
    "khronos",
    "migoox",
    "msaa",
    "nolint",
    "objs",
    "opengl",
    "raii",
    "rasterizer",
    "sdl",
    "shader",
    "shaders",
    "spirv",
    "spv",
    "srgb",
    "tparam",
    "tps",
    "ubo",
    "vbo",
    "vkren",
    "vma",
    "vsync",
    "wwindow",
    "xoffset",
    "yoffset",
]
