words = [
    "dsl",
    "emplaced",
    "eray",
    "glfw",
    "imgui",
    "migoox",
    "msaa",
    "nolint",
    "objs",
    "raii",
    "rasterizer",
    "sdl",
    "shader",
    "spirv",
    "tps",
    "vkren",
    "vsync",
]
