words = [
    "constexpr",
    "dsl",
    "emplaced",
    "eray",
    "glfw",
    "glfw's",
    "imgui",
    "infos",
    "khr",
    "khronos",
    "migoox",
    "msaa",
    "nolint",
    "objs",
    "raii",
    "rasterizer",
    "sdl",
    "shader",
    "spirv",
    "tps",
    "vkren",
    "vma",
    "vsync",
]
